name: CI Pipeline

on:
  pull_request:
    branches:
      [ main ]
    types:
      [ opened, synchronize, reopened ]

jobs:
  Continuous-Integration:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: testpw
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      SPRING_PROFILES_ACTIVE: local
      
      # Database Configuration
      DB_URL: jdbc:mysql://127.0.0.1:3306/testdb
      DB_USERNAME: root
      DB_PASSWORD: testpw
      DB_DRIVER: com.mysql.cj.jdbc.Driver
      JPA_DDL_AUTO: create-drop
      JPA_SHOW_SQL: true
      JPA_DIALECT: org.hibernate.dialect.MySQL8Dialect
      
      # Mail Configuration
      RESEND_KEY: temp
      RESEND_MAIL_SENDER: temp

    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: JDK 21 버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21

      - name: Gradle Wrapper 실행 권한 부여
        run: chmod +x ./gradlew

      - name: 전체 빌드 및 테스트
        run: ./gradlew clean build

      - name: Close PR, if build fail
        if: ${{ failure() }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ github.TOKEN }}
          script: |
            const pull_number = ${{ github.event.pull_request.number }}
            const updated_title = `[BUILD FAIL] ${{ github.event.pull_request.title }}`
            await github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pull_number,
              body: '빌드에 실패했습니다.',
              event: 'REQUEST_CHANGES'
            })
            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pull_number,
              title: updated_title,
              state: 'closed'
            })
